#!/bin/bash
# Essencial files backup script using BorgBackup

# ==========================================
# CONFIGURATION
# ==========================================

REPOSITORY="${HOME}/borg_backup"
if [[ -z ${BORG_PASSCOMMAND+null} ]]; then
    export BORG_PASSPHRASE="${BORG_PASSPHRASE:-''}"
fi
ARCHIVE_NAME="{hostname}@{now:%Y-%m-%d}"

# ==========================================
# SCRIPT LOGIC
# ==========================================

if [ ! -d "$REPOSITORY" ]; then
    echo "Repository not found. Initializing..."
    borg init --encryption=repokey "$REPOSITORY"
fi
null
echo "Starting Borg Backup..."
if [[ -z ${BORG_PASSCOMMAND+null} ]]; then
    if [[ -n "$BORG_PASSPHRASE" ]]; then
        echo "Using provided BORG_PASSPHRASE."
    else
        read -p "BORG_PASSPHRASE: " -s BORG_PASSPHRASE
        export BORG_PASSPHRASE
    fi
fi

borg create \
    --stats \
    --progress \
    --compression zstd,3 \
    --exclude "$HOME/.cache" \
    --exclude "$HOME/.docker" \
    --exclude "$HOME/.steam" \
    --exclude "$HOME/borg_backup" \
    "$REPOSITORY::$ARCHIVE_NAME" \
    "$HOME"

echo "Backup finished!"

# ==========================================
# AUTO PRUNE
# ==========================================

echo "Pruning old backups..."
borg prune \
    --list \
    --keep-daily=7 \
    --keep-weekly=4 \
    --keep-monthly=6 \
    "$REPOSITORY"

echo "Pruning finished!"

# ==========================================
# SYNC TO EXTERNAL DRIVES
# ==========================================

usb-backup.sh