#!/bin/bash
# execute in .pkr.hcl directory

PACKER_FILE_PATH="${1:-}"
BOX_NAME="${2:-packer$(date +%Y.%m.%d)}"
DIR_TO_CHECK="output"

touch /tmp/time_marker_mkbox

if [[ -z "${PACKER_FILE_PATH}" ]]; then
  echo "Usage: $0 <packer_file_path> [box_name]"
  exit 1
fi

if [[ ! -f "${PACKER_FILE_PATH}" ]]; then
  echo "Error: File '${PACKER_FILE_PATH}' not found."
  exit 1
fi

if packer validate "${PACKER_FILE_PATH}"; then
  echo "Packer template '${PACKER_FILE_PATH}' is valid."
else
  echo "Error: Packer template '${PACKER_FILE_PATH}' is invalid."
  exit 1
fi

packer fmt "${PACKER_FILE_PATH}"
packer build "${PACKER_FILE_PATH}"

find "${DIR_TO_CHECK}" -maxdepth 1 -type f -newer /tmp/time_marker_mkbox | while read -r new_file; do
  vagrant box add --name "${BOX_NAME}" "${new_file}"
done
rm -f /tmp/time_marker_mkbox