# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "mint-2026.05.31"
  config.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_udp: false, nfs_version: 4, mount_options: ["tcp", "nolock", "actimeo=2"]

  config.vm.provider :libvirt do |domain, override|
    domain.memory = 4096
      domain.cpus = 2
      domain.nested = true
      
      # Enable SPICE graphics and a virtual GPU
      domain.graphics_type = "spice"
      domain.video_type = "virtio"
      domain.video_vram = 256
      
      # Enable the SPICE channel for clipboard sharing and dynamic resizing
      domain.channel type: "spicevmc", target_name: "com.redhat.spice.0", target_type: "virtio"
  end
end
