# Default configuration for brudnopis
NOTE_FILE="${NOTE_FILE:=brudnopis.txt}"

readonly EDITOR="${EDITOR:=vim}"
readonly EDITOR_ARGS="${EDITOR_ARGS:=+}"
readonly GENERAL_NOTE_FILE="${GENERAL_NOTE_FILE:=${HOME}/Dokumenty/brudnopis_general.txt}"
readonly DATE_FORMAT="+%Y.%m.%d %A %R:%S"

note_dir="${PWD}"
find_dir="${PWD}"
repo_dir=$(git rev-parse --show-toplevel 2>/dev/null || echo '')

flag_force_local=false
flag_use_global=false
